# EDA — Subastas Públicas de Inmuebles en España
Fuente: Portal de Subastas del BOE (subastas.boe.es)<br>
Período analizado: Diciembre 2025

---
## Hipótesis
> *"La mayoría de los inmuebles subastados en el Portal del BOE 
> durante diciembre 2025 se ofertan por debajo del 50% de su valor 
> de tasación, lo que representa una oportunidad significativa de 
> compra para inversores y particulares"*

## Objetivo
Analizar el comportamiento de las subastas públicas de inmuebles 
en España: precios, descuentos sobre tasación, organismos 
convocantes y distribución geográfica.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración de visualizaciones
plt.rcParams['figure.figsize'] = (12, 5)
plt.rcParams['figure.dpi'] = 100
sns.set_theme(style='whitegrid')

# 1. VISUALIZACION

1.1 Carga del dataset de subastas que está en la ruta './data/subastas_inmuebles_dic2025.csv'

In [3]:
df = pd.read_csv('./data/subastas_inmuebles_dic2025.csv')

print(f'Dataset cargado')
print(f'Filas    : {df.shape[0]}')
print(f'Columnas : {df.shape[1]}')

Dataset cargado
Filas    : 1537
Columnas : 23

In [4]:
#Primera 5 filas
df.head()

,referencia,num_lotes_listado,organismo,expediente,estado,fecha_conclusion_listado,descripcion,url_detalle,id_sub,referencia_det,...,anuncio_boe,valor_subasta_eur,tasacion_eur,puja_minima_eur,tramo_pujas_eur,deposito_eur,fecha_inicio,fecha_conclusion,cuenta_expediente,forma_adjudicacion
0,SUB-RC-2025-3800100125018,1,Agencia Tributaria Canaria - Las Palmas de Gra...,NaN,Suspendida,NaN,URBANA: Número veinticinco. -Unidad de Alojami...,https://subastas.boe.es/detalleSubasta.php?idS...,SUB-RC-2025-3800100125018,SUB-RC-2025-3800100125018,...,BOE-B-2025-39962,105744.66,105744.66,NaN,1500.0,5287.23,NaN,NaN,NaN,NaN
1,SUB-AT-2025-24R4686001676,1,U.R. SUBASTAS VALENCIA - VALENCIA (AEAT),NaN,Finalizada y depósitos con reserva devueltos,01/12/2025 a las 18:00:00,"VIVIENDA. CL/ SIENA, 37 BJ J. 28027 - MADRID (...",https://subastas.boe.es/detalleSubasta.php?idS...,SUB-AT-2025-24R4686001676,SUB-AT-2025-24R4686001676,...,BOE-B-2025-41064,55110.30,311336.41,NaN,1000.0,2755.51,2025-11-11,2025-12-01,NaN,NaN
2,SUB-AT-2025-25R0886001398,1,U.R. SUBASTAS CATALUÑA - BARCELONA (AEAT),NaN,Finalizada y depósitos con reserva devueltos,01/12/2025 a las 18:00:00,SOLAR. UR FONT DEL BOSC 108 MEDIONA BARCELONA,https://subastas.boe.es/detalleSubasta.php?idS...,SUB-AT-2025-25R0886001398,SUB-AT-2025-25R0886001398,...,BOE-B-2025-41049,47400.00,79000.00,4740.00,1000.0,2370.00,2025-11-11,2025-12-01,NaN,NaN
3,SUB-AT-2025-25R0886001399,1,U.R. SUBASTAS CATALUÑA - BARCELONA (AEAT),NaN,Finalizada y depósitos con reserva devueltos,01/12/2025 a las 18:00:00,SOLAR. UR FONT DEL BOSC . C/ BELLOC 131 MEDION...,https://subastas.boe.es/detalleSubasta.php?idS...,SUB-AT-2025-25R0886001399,SUB-AT-2025-25R0886001399,...,BOE-B-2025-41050,49200.00,82000.00,4920.00,1000.0,2460.00,2025-11-11,2025-12-01,NaN,NaN
4,SUB-AT-2025-25R0886001455,1,U.R. SUBASTAS CATALUÑA - BARCELONA (AEAT),NaN,Finalizada y depósitos con reserva devueltos,01/12/2025 a las 18:00:00,100% PLENO DOMINIO DE GARAJE. PD/ DEL CAMP . 2...,https://subastas.boe.es/detalleSubasta.php?idS...,SUB-AT-2025-25R0886001455,SUB-AT-2025-25R0886001455,...,BOE-B-2025-41051,15264.48,15264.48,1526.45,500.0,763.22,2025-11-11,2025-12-01,NaN,NaN

In [5]:
#Tipos de datos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1537 entries, 0 to 1536
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   referencia                1537 non-null   str
 1   num_lotes_listado         1537 non-null   int64
 2   organismo                 1537 non-null   str
 3   expediente                1184 non-null   str
 4   estado                    1537 non-null   str
 5   fecha_conclusion_listado  1434 non-null   str
 6   descripcion               1495 non-null   str
 7   url_detalle               1537 non-null   str
 8   id_sub                    1537 non-null   str
 9   referencia_det            1537 non-null   str
 10  tipo_subasta              1537 non-null   str
 11  cantidad_reclamada_eur    1287 non-null   float64
 12  lotes                     1537 non-null   int64
 13  anuncio_boe               1537 non-null   str
 14  valor_subasta_eur         1303 non-null   float64
 15  tasacion_eur              1311 non-null   float64
 16  puja_minima_eur           341 non-null    float64
 17  tramo_pujas_eur           1094 non-null   float64
 18  deposito_eur              1311 non-null   float64
 19  fecha_inicio              1434 non-null   str
 20  fecha_conclusion          1434 non-null   str
 21  cuenta_expediente         1184 non-null   str
 22  forma_adjudicacion        226 non-null    str
dtypes: float64(6), int64(2), str(15)
memory usage: 276.3 KB

In [6]:
#Estadísticas básicas
df.describe()

,num_lotes_listado,cantidad_reclamada_eur,lotes,valor_subasta_eur,tasacion_eur,puja_minima_eur,tramo_pujas_eur,deposito_eur
count,1537.000000,1.287000e+03,1537.000000,1.303000e+03,1.311000e+03,3.410000e+02,1094.000000,1311.000000
mean,1.903709,6.800985e+05,1.903709,2.684248e+05,1.171393e+05,6.668486e+04,4790.698300,13639.208375
std,5.227242,1.173695e+07,5.227242,9.595952e+05,7.018234e+05,4.429601e+05,17141.102073,42719.117400
min,1.000000,0.000000e+00,1.000000,2.449100e+02,0.000000e+00,1.000000e+00,8.100000,0.000000
25%,1.000000,4.002853e+04,1.000000,5.832501e+04,0.000000e+00,8.500000e+02,1000.000000,2963.975000
50%,1.000000,1.020086e+05,1.000000,1.314096e+05,0.000000e+00,5.294110e+03,2258.815000,6747.430000
75%,1.000000,1.897034e+05,1.000000,2.265382e+05,7.850007e+04,2.250000e+04,3905.807500,11876.400000
max,76.000000,4.175205e+08,76.000000,1.827946e+07,1.588523e+07,6.500000e+06,325754.000000,814385.000000

1.2 Durante la vista al dataset se observa que aparentemente hay columnas que tienen los mismos datos, sera necesario verificarlos.

In [7]:
# ====== Verificar las 3 columnas posiblemente iguales ('referencia', 'id_sub', 'referencia_det') =======
print('=== REFERENCIAS ===')
print(f'¿referencia == id_sub?')
print(f'Iguales     : {(df["referencia"] == df["id_sub"]).sum()}')
print(f'Distintos   : {(df["referencia"] != df["id_sub"]).sum()}')
print(f'Nulos id_sub: {df["id_sub"].isna().sum()}')

print("---------------------------------")
print(f'¿referencia == referencia_det?')
print(f'Iguales             : {(df["referencia"] == df["referencia_det"]).sum()}')
print(f'Distintos           : {(df["referencia"] != df["referencia_det"]).sum()}')
print(f'Nulos referencia_det: {df["referencia_det"].isna().sum()}')

print("---------------------------------")
# Ver ejemplos de los 3 juntos
print('Muestra de las 3 columnas:')
df[['referencia', 'id_sub', 'referencia_det']].head(5)

=== REFERENCIAS ===
¿referencia == id_sub?
Iguales     : 1537
Distintos   : 0
Nulos id_sub: 0
---------------------------------
¿referencia == referencia_det?
Iguales             : 1537
Distintos           : 0
Nulos referencia_det: 0
---------------------------------
Muestra de las 3 columnas:

,referencia,id_sub,referencia_det
0,SUB-RC-2025-3800100125018,SUB-RC-2025-3800100125018,SUB-RC-2025-3800100125018
1,SUB-AT-2025-24R4686001676,SUB-AT-2025-24R4686001676,SUB-AT-2025-24R4686001676
2,SUB-AT-2025-25R0886001398,SUB-AT-2025-25R0886001398,SUB-AT-2025-25R0886001398
3,SUB-AT-2025-25R0886001399,SUB-AT-2025-25R0886001399,SUB-AT-2025-25R0886001399
4,SUB-AT-2025-25R0886001455,SUB-AT-2025-25R0886001455,SUB-AT-2025-25R0886001455

In [8]:
# ====== Verificar las 2 columnas posiblemente iguales ('num_lotes_listado', 'lotes')=======

print('=== LOTES ===')
print(f'¿num_lotes_listado == lotes?')
iguales = (df['num_lotes_listado'] == df['lotes']).sum()
distintos = (df['num_lotes_listado'] != df['lotes']).sum()
print(f'Iguales   : {iguales}')
print(f'Distintos : {distintos}')

print("---------------------------------")
# Ver ejemplos de los 2 juntos
print('Muestra de las 2 columnas:')
df[['num_lotes_listado', 'lotes']].head(5)

=== LOTES ===
¿num_lotes_listado == lotes?
Iguales   : 1537
Distintos : 0
---------------------------------
Muestra de las 2 columnas:

   num_lotes_listado  lotes
0                  1      1
1                  1      1
2                  1      1
3                  1      1
4                  1      1

In [9]:
# ====== Verificar las 2 columnas posiblemente iguales ('fecha_conclusion_listado', 'fecha_conclusion')=======

print('=== FECHA CONCLUSION ===')
print(f'fecha_conclusion_listado == fecha_conclusion?')
iguales = (df['fecha_conclusion_listado'] == df['fecha_conclusion']).sum()
distintos = (df['fecha_conclusion_listado'] != df['fecha_conclusion']).sum()
print(f'Iguales   : {iguales}')
print(f'Distintos : {distintos}')

print("---------------------------------")
# Ver ejemplos de los 2 juntos
print('Muestra de las 2 columnas:')
df[['fecha_conclusion_listado', 'fecha_conclusion']].head(7)

=== FECHA CONCLUSION ===
fecha_conclusion_listado == fecha_conclusion?
Iguales   : 0
Distintos : 1537
---------------------------------
Muestra de las 2 columnas:

    fecha_conclusion_listado fecha_conclusion
0                        NaN              NaN
1  01/12/2025 a las 18:00:00       2025-12-01
2  01/12/2025 a las 18:00:00       2025-12-01
3  01/12/2025 a las 18:00:00       2025-12-01
4  01/12/2025 a las 18:00:00       2025-12-01
5  01/12/2025 a las 18:00:00       2025-12-01
6  01/12/2025 a las 18:00:00       2025-12-01

1.3 Elimando columnas duplicadas.

In [10]:
# Columnas a eliminar y motivo
columnas_eliminar = [
    'id_sub',                  # idéntica a 'referencia'
    'referencia_det',          # idéntica a 'referencia'
    'num_lotes_listado',       # idéntica a 'lotes'
    'fecha_conclusion_listado' # duplicada en formato sucio '01/12/2025 a las 18:00:00'  (texto con hora)
]

df = df.drop(columns=columnas_eliminar).copy()

print(f'Columnas eliminadas: {columnas_eliminar}')
print(f'Columnas restantes : {df.shape[1]}')
print(f'Shape actual       : {df.shape}')

Columnas eliminadas: ['id_sub', 'referencia_det', 'num_lotes_listado', 'fecha_conclusion_listado']
Columnas restantes : 19
Shape actual       : (1537, 19)

In [11]:
print('Columnas actuales:')
for i, col in enumerate(df.columns):
    print(f'{i}.{col}')

Columnas actuales:
0.referencia
1.organismo
2.expediente
3.estado
4.descripcion
5.url_detalle
6.tipo_subasta
7.cantidad_reclamada_eur
8.lotes
9.anuncio_boe
10.valor_subasta_eur
11.tasacion_eur
12.puja_minima_eur
13.tramo_pujas_eur
14.deposito_eur
15.fecha_inicio
16.fecha_conclusion
17.cuenta_expediente
18.forma_adjudicacion

1.4 Eliminando columnas que no aportan al análisis

In [12]:
columnas_eliminar = [
    'url_detalle', # URL
    'anuncio_boe'  # código interno del BOE
]

df = df.drop(columns= columnas_eliminar).copy()
print(f'Columnas a eliminar: {columnas_eliminar}')
print(f'Shape actual:        {df.shape}')

Columnas a eliminar: ['url_detalle', 'anuncio_boe']
Shape actual:        (1537, 17)

In [13]:
df.head()

,referencia,organismo,expediente,estado,descripcion,tipo_subasta,cantidad_reclamada_eur,lotes,valor_subasta_eur,tasacion_eur,puja_minima_eur,tramo_pujas_eur,deposito_eur,fecha_inicio,fecha_conclusion,cuenta_expediente,forma_adjudicacion
0,SUB-RC-2025-3800100125018,Agencia Tributaria Canaria - Las Palmas de Gra...,NaN,Suspendida,URBANA: Número veinticinco. -Unidad de Alojami...,RECAUDACIÓN TRIBUTARIA,315821.33,1,105744.66,105744.66,NaN,1500.0,5287.23,NaN,NaN,NaN,NaN
1,SUB-AT-2025-24R4686001676,U.R. SUBASTAS VALENCIA - VALENCIA (AEAT),NaN,Finalizada y depósitos con reserva devueltos,"VIVIENDA. CL/ SIENA, 37 BJ J. 28027 - MADRID (...",AGENCIA TRIBUTARIA,NaN,1,55110.30,311336.41,NaN,1000.0,2755.51,2025-11-11,2025-12-01,NaN,NaN
2,SUB-AT-2025-25R0886001398,U.R. SUBASTAS CATALUÑA - BARCELONA (AEAT),NaN,Finalizada y depósitos con reserva devueltos,SOLAR. UR FONT DEL BOSC 108 MEDIONA BARCELONA,AGENCIA TRIBUTARIA,NaN,1,47400.00,79000.00,4740.00,1000.0,2370.00,2025-11-11,2025-12-01,NaN,NaN
3,SUB-AT-2025-25R0886001399,U.R. SUBASTAS CATALUÑA - BARCELONA (AEAT),NaN,Finalizada y depósitos con reserva devueltos,SOLAR. UR FONT DEL BOSC . C/ BELLOC 131 MEDION...,AGENCIA TRIBUTARIA,NaN,1,49200.00,82000.00,4920.00,1000.0,2460.00,2025-11-11,2025-12-01,NaN,NaN
4,SUB-AT-2025-25R0886001455,U.R. SUBASTAS CATALUÑA - BARCELONA (AEAT),NaN,Finalizada y depósitos con reserva devueltos,100% PLENO DOMINIO DE GARAJE. PD/ DEL CAMP . 2...,AGENCIA TRIBUTARIA,NaN,1,15264.48,15264.48,1526.45,500.0,763.22,2025-11-11,2025-12-01,NaN,NaN

1.5 Corrigiendo tipo de datos

In [21]:
#==== Fechas a tipo datetime=======
df['fecha_inicio']= pd.to_datetime(df['fecha_inicio'], errors= 'coerce') #coerce --> si no puede convertir un valor a fecha pone NaT
df['fecha_conclusion']= pd.to_datetime(df['fecha_conclusion'], errors= 'coerce')

#=====Verificamos cambios ======
print(df.dtypes)

referencia                           str
organismo                            str
expediente                           str
estado                               str
descripcion                          str
tipo_subasta                         str
cantidad_reclamada_eur           float64
lotes                              int64
valor_subasta_eur                float64
tasacion_eur                     float64
puja_minima_eur                  float64
tramo_pujas_eur                  float64
deposito_eur                     float64
fecha_inicio              datetime64[us]
fecha_conclusion          datetime64[us]
cuenta_expediente                    str
forma_adjudicacion                   str
dtype: object

In [22]:
df.head()

,referencia,organismo,expediente,estado,descripcion,tipo_subasta,cantidad_reclamada_eur,lotes,valor_subasta_eur,tasacion_eur,puja_minima_eur,tramo_pujas_eur,deposito_eur,fecha_inicio,fecha_conclusion,cuenta_expediente,forma_adjudicacion
0,SUB-RC-2025-3800100125018,Agencia Tributaria Canaria - Las Palmas de Gra...,NaN,Suspendida,URBANA: Número veinticinco. -Unidad de Alojami...,RECAUDACIÓN TRIBUTARIA,315821.33,1,105744.66,105744.66,NaN,1500.0,5287.23,NaT,NaT,NaN,NaN
1,SUB-AT-2025-24R4686001676,U.R. SUBASTAS VALENCIA - VALENCIA (AEAT),NaN,Finalizada y depósitos con reserva devueltos,"VIVIENDA. CL/ SIENA, 37 BJ J. 28027 - MADRID (...",AGENCIA TRIBUTARIA,NaN,1,55110.30,311336.41,NaN,1000.0,2755.51,2025-11-11,2025-12-01,NaN,NaN
2,SUB-AT-2025-25R0886001398,U.R. SUBASTAS CATALUÑA - BARCELONA (AEAT),NaN,Finalizada y depósitos con reserva devueltos,SOLAR. UR FONT DEL BOSC 108 MEDIONA BARCELONA,AGENCIA TRIBUTARIA,NaN,1,47400.00,79000.00,4740.00,1000.0,2370.00,2025-11-11,2025-12-01,NaN,NaN
3,SUB-AT-2025-25R0886001399,U.R. SUBASTAS CATALUÑA - BARCELONA (AEAT),NaN,Finalizada y depósitos con reserva devueltos,SOLAR. UR FONT DEL BOSC . C/ BELLOC 131 MEDION...,AGENCIA TRIBUTARIA,NaN,1,49200.00,82000.00,4920.00,1000.0,2460.00,2025-11-11,2025-12-01,NaN,NaN
4,SUB-AT-2025-25R0886001455,U.R. SUBASTAS CATALUÑA - BARCELONA (AEAT),NaN,Finalizada y depósitos con reserva devueltos,100% PLENO DOMINIO DE GARAJE. PD/ DEL CAMP . 2...,AGENCIA TRIBUTARIA,NaN,1,15264.48,15264.48,1526.45,500.0,763.22,2025-11-11,2025-12-01,NaN,NaN

In [26]:
#============Nulos por columna=========
nulos = (df.isnull().sum() / len(df) * 100).round(2)
nulos = nulos[nulos > 0].sort_values(ascending=False)

print('Columnas con valores nulos (%):')
print(nulos.to_string())

Columnas con valores nulos (%):
forma_adjudicacion        85.30
puja_minima_eur           77.81
tramo_pujas_eur           28.82
expediente                22.97
cuenta_expediente         22.97
cantidad_reclamada_eur    16.27
valor_subasta_eur         15.22
deposito_eur              14.70
tasacion_eur              14.70
fecha_conclusion           6.70
fecha_inicio               6.70
descripcion                2.73